# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../../../components/gke/resources/gpu/1-L4

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment